# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

def pods
  pod 'Moya', '~> 14.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'
  pod 'SwiftGen', '~> 6.0'
  pod 'SwiftLint'
  pod 'lottie-ios'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
end

target 'HACKER' do
  pods
end

target 'HACKERTests' do
  pods
end

target 'HACKERUITests' do
  pods
end
